language: cpp
env:
  global:
  - FORCE_INSTALL=1

matrix:
  include:

  - os: osx
    name: "Build macOS XCODE5"
    osx_image: xcode10.2
    compiler: clang

    script:
    - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl mingw-w64
    - "./build_duet.tool"
    - "./build_oc.tool"
    
    deploy:
      provider: releases
      user: "hjp521"
      password: "Hjp581200"
      skip_cleanup: true
      file:"Binaries/*.zip"
      file_glob: true
      on:
        tags: true
